language: python
python:
  - 3.6
install:
  - pip install -q -r requirements-dev.txt
script:
  - flake8
  - pytest omdbapi --cov=omdbapi
before_install:
  - pip install codecov
after_success:
  - codecov